### ISSUE TITLE
FlowLayout Error in iOS 13.7

### ISSUE THREAD

**Issue by AhmedAmineZribi** [globulus/swiftui-flow-layout#5]
then I used package of FlowLayout  in my project and I run the app with iOS 13.7, the app crash.
Could you please make changes for  < iOS 14
Thank you 
[](url)
<img width="820" alt="FlowLayout 1 0 3" src="https://user-images.githubusercontent.com/15227156/141163333-d4af051a-022a-4969-8cd3-ac93c76fba0d.png">

**Comment by gordan-glavas-codecons** [comment]
@AhmedAmineZribi I can run the code normally on a 13.7 emulator:

![Screenshot 2021-11-11 at 10 13 07](https://user-images.githubusercontent.com/6662291/141270769-83aa4db0-e395-461c-816b-3937c7e4846f.png)

and I do run it in live projects targeting iOS 13, so I'd guess that the issue is in the unfortunate combo of SwiftUI 1 and the rest of your codebase. I'd have to see the view that actually contains the FlowLayout to tell more, but iOS 13 is known for having issues with nested GeometryReaders.

**Comment by AhmedAmineZribi** [comment]
is that FlowLayout 1.0.0 or 1.0.3 ? 
in my side I used with 1.0.0 and I have error I think it related to GeometryReaders in this function : 
`  private func viewHeightReader(_ binding: Binding<CGFloat>) -> some View {
    return GeometryReader { geo -> Color in
      DispatchQueue.main.async {
        binding.wrappedValue = geo.frame(in: .local).size.height
      }
      return .clear
    }
  }`

<img width="393" alt="flow layout success 14.3" src="https://user-images.githubusercontent.com/15227156/141272514-2c9636c5-f743-4b29-b591-444159ff836b.png">

<img width="429" alt="flow layout error 13.7" src="https://user-images.githubusercontent.com/15227156/141273116-97f37242-98ff-4e09-992e-42a05e2fd321.png">

**Comment by gordan-glavas-codecons** [comment]
It's 1.0.3, always use the latest version as it contains bug fixes and additional improvements compared to previous ones.

**Comment by AhmedAmineZribi** [comment]
Hello @gordan-glavas-codecons, I update my package to 13.7 and still have the same issues in func viewHeightReader. The frame in geo . you can see Screen shot 

<img width="1056" alt="follow layout" src="https://user-images.githubusercontent.com/15227156/141613480-1bf72e32-7e76-4f68-9135-c1a40ad7986b.png">

In my case I use flow layout not in all frame like you make, as you see in my last screen shot it was in a section . 

### The solution is  : 
   `binding.wrappedValue = geo.size.height`

### instead for this :
   `binding.wrappedValue = geo.frame(in: .local).size.height`

Can you please make this changes ?

**Comment by gordan-glavas-codecons** [comment]
There is an important difference between the `geo.size.height` and `geo.frame(in: .local).size.height`, with the former being the *expected* size, and latter being the actually *measured* one, hence just using the former would be wrong for most use-cases.

The issue you're seeing is a result of stacked GeometryReaders not working on iOS 13 and is somewhat specific to your layout. I recommend creating a fork of this repo and making the change in it, since I can't make the change here without compromising stability.
